<a href="https://colab.research.google.com/github/LeadShadow/hw7_data_science/blob/main/HW7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... done
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=cecd2eaf154194362d06bfccfbbccbae0f1cf25de08077b0e32b3676ab0a7fdf
  Stored in directory: /root/.cache/pip/wheels/14/25/f7/1cc0956978ae479e75140219088deb7a36f60459df242b1a72
Successfully built sklearn


In [3]:
from sklearn.datasets import load_wine

wine_dataset = load_wine()
wine_dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [4]:
x = wine_dataset.data
y = wine_dataset.target

In [5]:
print(x.shape)
print(y.shape)

(178, 13)
(178,)


In [6]:
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.model_selection import cross_val_score

In [8]:
log = LogisticRegression(solver='lbfgs', max_iter=5000)
results = cross_val_score(log, x, y, cv=5)

In [10]:
mean = np.mean(results)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=38)
log.fit(X_train, y_train)
y_pred = log.predict(X_test)

In [13]:
y_pred

array([2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0,
       1, 0, 2, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1,
       1, 1, 1, 2, 1, 0, 1, 0, 2, 2])

In [12]:
y_test

array([2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0, 1, 2, 1, 0, 1,
       2, 0, 2, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1,
       1, 1, 1, 2, 2, 0, 1, 0, 2, 2])

In [15]:
log.score(X_test, y_test)

0.9444444444444444

In [17]:
accuracy_score(y_pred, y_test)

0.9444444444444444

In [18]:
confusion_matrix(y_pred, y_test)

array([[19,  1,  0],
       [ 0, 19,  2],
       [ 0,  0, 13]])

In [20]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97        20
           1       0.95      0.90      0.93        21
           2       0.87      1.00      0.93        13

    accuracy                           0.94        54
   macro avg       0.94      0.95      0.94        54
weighted avg       0.95      0.94      0.94        54

